Update faq.md
JunoLab/JunoDocs.jl pull request #11
Opened 2016-11-22 17:37 UTC by Balinus

Added "Advanced topics" in faq.md.
Added "Connecting to an external julia session on a remote machine".

2016-11-22 18:27 UTC, pfitzseb requested changes
Thanks for writing this up!

2016-11-22 18:27 UTC, pfitzseb commented on docs/src/man/faq.md
> +2. In Atom/Juno : Julia-client : connect to external process (Juno will then tell you which port to use locally --> we'll call it **PORT#2**)
This should probably be a code block, not bold:
```
`Port#2`
```
Same below.

2016-11-22 18:27 UTC, pfitzseb commented on docs/src/man/faq.md
> +3. Open a local terminal and connect to your remote server : "**ssh -R PORT#1:localhost:PORT#2 your.server.com**"
Maybe note that that'll only work on unixes. For windows, `netsh` [should work](http://stackoverflow.com/questions/11525703/port-forwarding-in-windows).

2016-11-22 18:27 UTC, pfitzseb commented on docs/src/man/faq.md
> +Use case : local installation of Juno with a remote julia session
I'd remove the space before the semi-colon; looks strange to me. Below as well.

2016-11-22 18:47 UTC, Balinus commented on docs/src/man/faq.md
> +Use case : local installation of Juno with a remote julia session
There's no space in english between a colon and the previous word. I agree it looks strange though, but I think we should follow english punctuation rules.

2016-11-22 18:54 UTC, Balinus commented on docs/src/man/faq.md
> +3. Open a local terminal and connect to your remote server : "**ssh -R PORT#1:localhost:PORT#2 your.server.com**"
Good idea. Although I can't comment on the windows procedure. I will link the thread you mention.

2016-11-22 18:54 UTC, Balinus commented on docs/src/man/faq.md
> +2. In Atom/Juno : Julia-client : connect to external process (Juno will then tell you which port to use locally --> we'll call it **PORT#2**)
ok!

2016-11-22 19:02 UTC, pfitzseb commented on docs/src/man/faq.md
> +Use case : local installation of Juno with a remote julia session
> There's no space in english between a colon and the previous word.

But that's what I said? And you *do* have a space there.

2016-11-22 19:04 UTC, Balinus commented on docs/src/man/faq.md
> +Use case : local installation of Juno with a remote julia session
oh! I misread and I was sure there were no space to begin with. Sorry, my bad!

2016-11-22 19:06 UTC, Balinus commented on docs/src/man/faq.md
> +Use case : local installation of Juno with a remote julia session
It should be OK with the latest commit: https://github.com/JunoLab/JunoDocs.jl/pull/11/commits/8f21b877a8229c78ba38fdadc1f502161044db7c

2016-11-23 09:03 UTC, pfitzseb approved these changes

2016-11-23 09:03 UTC, merged